### ISSUE TITLE
VALIDACION 

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-tim-mlnce#2]
[Validación de DRS 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-tim-mlnce/files/10844646/Validacion.de.DRS.1.pdf)

**Comment by Heidi-19** [comment]
Calificación: 16.4%

Portada - 25
Procedimiento 22 - Falta descripción de imágenes
Figuras 15 - Tiene 10 figuras
Resultados 20 - Tiene 8 líneas de conclusión

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
